// Data service layer - replaced Supabase with Google Apps Script endpoint
// All functions are now backed by cached JSON data fetched from Google Apps Script
// This file re-exports everything from the data service for backward compatibility

export {
  initializeDataService,
  initializeKpiDataService,
  populateDashboardMetrics,
  getDashboardMetrics,
  getDashboardStats,
  getMonthlyPerformance,
  getHubStats,
  getKpiGradeDistribution,
  getAllUniqueHubsAndRegions,
  getPerformanceRecordsPaginated,
  getPerformanceRecords,
  getPerformanceRecordsByRiderId,
  getRecentPerformanceRecords,
  createPerformanceRecord,
  updatePerformanceRecord,
  deletePerformanceRecord,
  getPerformanceRecordByRiderAndDate,
  getPerformanceRecordsByDateRange,
  deleteAllPerformanceRecords,
  getKpiRecordsPaginated,
  getKpiRecords,
  getRecentKpiRecords,
  createKpiRecord,
  updateKpiRecord,
  deleteKpiRecord,
  deleteAllKpiRecords,
  batchInsertKpiRecords,
  batchInsertPerformanceRecords,
  getRidersPaginated,
  getRiders,
  getRiderHubStats,
  getDistinctPerformanceRegions,
  getUniqueRiders,
  getUniqueHubs,
  getAllUniqueHubs,
  getClusterLeaders,
  createClusterLeader,
  updateClusterLeader,
  deleteClusterLeader,
  refreshRiders,
  syncRidersFromPerformance,
  insertSinglePerformanceRecord,
  syncClusterToKpiRecords,
  clearClusterFromKpiRecords,
  checkHubsInKpiRecords,
  getFuelManagementRiders,
  getCachedData,
  isDataLoading,
  getLoadError,
  testEndpointConnection,
  reloadDataService
} from './dataService'
